Artistic Style Transfer using CycleGAN
smaranjitghose/ArtCV pull request #69
Opened 2021-01-29 17:38 UTC by BlueBlaze6335

#68  ### Generating Van Gogh style pictures from random normal pictures !!

2021-01-29 17:42 UTC, BlueBlaze6335 commented
@smaranjitghose  dada please check the  pr !!

2021-01-30 23:04 UTC, smaranjitghose requested changes

2021-01-30 23:04 UTC, smaranjitghose commented on Artistic Style Transfer with CycleGAN/Readme.md
> +* In this [notebook](https://colab.research.google.com/drive/19t6m05nv7gnVdRZMkD-XZnaWUIsKcKZF?usp=sharing) we will explore the Artistry of the GANs , that is we will create Van Gogh Style pictures ,
Not Required.

Just put a section in the readme as Style Transfer and have three columns: Content, Style and Output

All images should be in assets folder

2021-01-30 23:04 UTC, smaranjitghose commented on Artistic Style Transfer with CycleGAN/Readme.md
> +
Add a script that takes in a content image, style image (paths using argparse) and generates the output using the cyclegan used in the notebook above. Use tqdm for colorful progress bars

2021-02-01 08:42 UTC, BlueBlaze6335 commented
I am having a problem in pushing the changed files , thats why i am closing this and i will add a new pr !! Sorry for the inconvenience @smaranjitghose .

2021-02-01 08:42 UTC, closed without merging